<title>Coinflip - by Echo</title>
<?php
 include 'settings.php';
?>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    var STEAMID = '<?php echo $user['steamid']; ?>';
    var TRADELINK = '<?php echo $user['tradelink']; ?>';
  </script>

  <script src="assets/js/jquery-3.2.1.js"></script>
  <script src="assets/js/jquery.cookie.js"></script>
  <script src="assets/js/jquery.dataTables.min.js"></script>
  <script src="assets/js/socket.io-1.4.5.js"></script>
  <script src="assets/js/cryptojs.js"></script>
  <script src="assets/js/notify.js"></script>
  <script src="assets/js/tinysort.js"></script>
  <script src="assets/js/app.js?v<?=time()?>"></script>
  <script src="assets/js/countdownHackerTimer.js"></script>
  <script src="assets/js/countTo.js"></script>

  <script>
    $.notify.defaults({
      clickToHide: true,
      autoHide: true,
      autoHideDelay: 2000,
      arrowShow: true,
      arrowSize: 177,
      position: 'top center',
      elementPosition: 'top center',
      globalPosition: 'top center',
      style: 'bootstrap',
      className: 'error',
      showAnimation: 'slideToggle',
      showDuration: 600,
      hideAnimation: 'slideToggle',
      hideDuration: 600,
      gap: 2
    });
  </script>
  <link rel="stylesheet" type="text/css" href="assets/css/app.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/font-awesome.min.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/animate.min.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/w3.css?v=<?=time()?>">
</head>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/coinflip"><img src="assets/images/logonew.png" class="header-logo"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav menu header-menu">
          <?php include 'Header.php'; ?>
        </ul> 

      <ul class="nav navbar-nav navbar-right header-menu">  
    <li style="
    margin-top: 10px;
    padding: 5px;
    margin-top: 5px;
"> 
  <?php
  if($user)
  { ?>

<div class="dropdown">
    <button class="dropbtn"><img width="32px" height="32px" style="width: 60px; height: 60px; border: 2px solid #5d4841; margin-right: 10px; border-radius: 100%; overflow: hidden; flex-shrink: 0;" src="<?=$user['avatar']?>"> <span class="profile-name"><?=$user['name']?> <span class="caret"></span></button>
  <div class="dropdown-content">
  <ul style="list-style: none;display: inline;">
      <?php include 'ProfileSettings.php'; ?>
    </ul>

    </div>
    </div>  
  <?php }else{ ?>
    <a href="login.php" style="padding: 2px 5px 0 5px; "><img src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png"></a>
  <?php } ?>
    </li>
    
      </ul>
    </div>
  </div>
</nav>

<body class="hellos">



<div class="container" style="width: 1170px;">

    <div class="starter-template" style="text-align:left;margin-top:100px;">

    <p style="color:#1a8a49;">To make sure each and every game presented on our website are fairly random we ve introducing you to our Provably Fair system.</p>

      <h3>Selecting the winner:</h3>

      <p>
        The round secret is generated at the beginning of the round but only shown at the end, and it's meant to encrpyt the winner percentage and allow you to verify the winning ticket via the round identifier.<br>
    The round hash is an md5 string that is given at the beginning of the round, it is generated by joining the round secret with the winner percentage, separated by a "-", so a round hash is an md5 encrypted string of [roundSecret]-[winningPercentage]</p>
      <p>Here is how the winner ticket is counted</p>
      <p class="alert alert-info">CryptoJS.AES.decrypt(codeCrypted, hash+secret).toString(CryptoJS.enc.Utf8);</p>

      <h3>Round Hash:</h3>

      <p style="font-size:14px;">The hash is an AES encryption of percentage.
      When the round is over, the secret is revealed.<br>You can verify that the hash matches with them with filling correctly the form below.</p>

      <h3>Round hash verify:</h3>
      <p style="font-size:14px;">You can verify each round here. If the parameters are correct, it displays the winner number of the round.</p>
      <div class="panel panel-default">
        <div class="panel-body">
          <form action="" method="post" id="form" class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="hash">Hash:</label>
            </div>
            <div class="col-sm-10">
              <input name="hash" class="form-control" id="hash" value="">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="secret">Secret:</label>
            </div>
            <div class="col-sm-10">
              <input name="secret" class="form-control" id="secret" value="">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="tickets">Tickets:</label>
            </div>
            <div class="col-sm-10">
              <input name="tickets" class="form-control" id="tickets" value="">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"></div>
            <div class="col-sm-10"><button type="button" name="form" id="findWinningTicket" class="btn btn-success">Check</button></div>
          </div>
          </form>
        </div>
      </div>

    </div>

  </div>


<script>
$('#findWinningTicket').click(function() {
  var hash = $('#hash').val();
  var secret = $('#secret').val();

   if(hash && secret) {
    $.ajax({
     url:"/getWinner.php?hash="+hash+"&secret="+secret,
     success:function(data){  
      try{
       data = JSON.parse(data);
       if(data.success){
          var cryptedCode = CryptoJS.AES.encrypt(data.winner.toString(), hash.concat(secret)).toString();

          var winnerCorrect = CryptoJS.AES.decrypt(cryptedCode, hash.concat(secret)).toString(CryptoJS.enc.Utf8);

          if(winnerCorrect = data.winner)
          {
            $.notify('This round is corrected! Winner is player ' + data.winner, 'success');
          }
          else
          {
            $.notify('This round is not corrected', 'success');
          }
        }else{
         $.notify(data.error, 'success');
       }
      }catch(err){
        $.notify(err, 'success');
      }
     },
     error:function(err){
        $.notify(err, 'success');
     }
    });
   } else {
    $.notify('Error: Complete all fields', 'success');
   }

});
</script>


<!-- ALLL MODALS -->
<?php include 'Modals.php'; ?>
<!-- ALL MODALS -->



</body>